channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - pyg
dependencies:
  - python==3.9.*
  - cmake
  - pybind11
  - pytorch=2.1.0=py3.9_cuda12.1*
  - pytorch3d
  - torchvision
  - torchaudio
  - pyg
  - pytorch-cluster
  - pytorch-scatter
  - exa # optional: nice ls
  - fzf # optional: fancy ctrl + R
  - pip
  - pip:
    - numpy <1.24 # certain deprecated operations were used in other deps
    - scipy
    - sophuspy
    - pybullet
    - trimesh<4
    - pytest
    - scikit-image
    - scikit-fmm
    - scikit-learn
    - numpy-quaternion
    - natsort
    - frozendict
    # Robots
    - opencv-python
    - pin>=2.6.17
    # Neural networks
    - openai-clip
    - timm
    - pandas>=2
    - mss
    # visualizations and debugging
    - matplotlib>=3
    # Command line tools
    - click
    # data tools
    - pillow<10.0.0
    - atomicwrites
    - loguru
    - yacs
    - h5py>=3.9
    - imageio
    - pygifsicle
    - pynput
      # - git+https://github.com/openai/CLIP.git
    - open3d>=0.17
    # For MiDaS
    #- imutils
